{
  "name": "pulsa-app",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~52.0.0",
    "expo-status-bar": "~2.0.0",
    "react": "18.2.0",
    "react-native": "0.76.0",
    "@react-navigation/native": "^7.0.0",
    "@react-navigation/native-stack": "^7.0.0",
    "react-native-screens": "~4.0.0",
    "react-native-safe-area-context": "4.10.0",
    "react-native-gesture-handler": "~2.20.0",
    "@react-navigation/bottom-tabs": "^7.0.0",
    "firebase": "11.0.0",
    "react-native-paper": "^5.10.0",
    "react-native-vector-icons": "^10.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.24.0"
  },
  "private": true
}
